#!/usr/bin/env bash
#ddev-generated
# Remove the line above if you don't want this file to be overwritten when you run
# ddev add-on get julienloizelet/ddev-playwright
#
# This file comes from https://github.com/julienloizelet/ddev-playwright
#
## Description: Run playwright command
## Usage: playwright [options] [command]
## Example: "ddev playwright test"
cd /var/www/html || exit 1
cd "${PLAYWRIGHT_TEST_DIR}" || exit 1

export PLAYWRIGHT_BROWSERS_PATH=0
export NODE_PATH=/deps/node_modules

if [[ "$1" == "show-report" ]]; then
  echo ""
  echo -e "\033[1;44m\033[1;97m  Playwright Report  \033[0m"
  echo -e "\033[1;96m  https://${VIRTUAL_HOST}:9323\033[0m"
  echo ""

  playwright show-report --host=0.0.0.0 Tests/Playwright/playwright-report
fi

playwright "$@"
