categories:
  Formcycle:
    label: 'Formcycle'

settings:
  formcycle.url:
    category: Formcycle
    label: 'Server URL'
    type: string
    description: 'The URL of the formcycle server'
    default: ''

  formcycle.clientId:
    category: Formcycle
    label: 'Client ID'
    type: string
    description: 'The formcycle client ID'
    default: ''

  formcycle.detailPid:
    category: Formcycle
    label: 'Detail page PID'
    type: number
    description: 'The PID where the detail plugin is located.'
    default: 0

  formcycle.storagePid:
    category: Formcycle
    label: 'Storage PID'
    type: number
    description: 'The PID where imported form data is stored'
    default: 0

  formcycle.defaultIntegrationMode:
    category: Formcycle
    label: 'Default integration mode'
    type: string
    description: 'The default mode for integrating the formcycle form'
    default: 'integrated'
    enum:
      integrated: 'Integrated'
      ajax_typo3: 'Ajax Typo3'
      ajax_formcycle: 'Ajax Formcycle'
      iframe: 'Iframe'
