#!/usr/bin/env bash
# shellcheck disable=SC2086
set -e

## Description: Initialize TYPO3 installation
## Usage: init-typo3
## Example: ddev init-typo3

readonly dbHost="db"
readonly dbUser="db"
readonly dbPassword="db"
readonly dbName="db"
readonly dbCredentials="-h${dbHost} -u${dbUser} -p${dbPassword}"
readonly fixturePath="/var/www/html/Tests/Acceptance/Fixtures"
readonly typo3Binary="/var/www/html/vendor/bin/typo3"
readonly typo3cmsBinary="/var/www/html/vendor/bin/typo3cms"

function _progress() {
    printf "%s... " "$1"
}

function _done() {
    printf "\e[32mDone\e[39m\n"
}

# Create empty database
_progress "Creating empty database"
mysql -Nse "SHOW TABLES" $dbCredentials "$dbName" | while read -r table; do
    mysql -e "DROP TABLE ${table}" $dbCredentials "$dbName"
done
_done

# Prepare setup environment
export TYPO3_DB_DRIVER=mysqli
export TYPO3_DB_USERNAME="$dbUser"
export TYPO3_DB_PASSWORD="$dbPassword"
export TYPO3_DB_PORT=3306
export TYPO3_DB_HOST="$dbHost"
export TYPO3_DB_DBNAME="$dbName"
export TYPO3_SETUP_ADMIN_EMAIL=admin@example.com
export TYPO3_SETUP_ADMIN_USERNAME=admin
export TYPO3_SETUP_ADMIN_PASSWORD=Passw0rd!
export TYPO3_SERVER_TYPE=other
export TYPO3_PROJECT_NAME="EXT:xm_formcycle"

export TYPO3_INSTALL_DB_DRIVER=mysqli
export TYPO3_INSTALL_DB_USER="$dbUser"
export TYPO3_INSTALL_DB_PASSWORD="$dbPassword"
export TYPO3_INSTALL_DB_PORT=3306
export TYPO3_INSTALL_DB_HOST="$dbHost"
export TYPO3_INSTALL_DB_DBNAME="$dbName"
export TYPO3_INSTALL_ADMIN_USER=admin
export TYPO3_INSTALL_ADMIN_PASSWORD=Passw0rd!
export TYPO3_INSTALL_SITE_SETUP_TYPE="no"
export TYPO3_INSTALL_WEB_SERVER_CONFIG="apache"
export TYPO3_INSTALL_SITE_NAME="EXT:xm_formcycle"
export TYPO3_INSTALL_DB_UNIX_SOCKET=""

# Set up environment
_progress "Setting up TYPO3 installation"
# TYPO3 v11
if [ -f "$typo3cmsBinary" ]; then
    "$typo3cmsBinary" install:setup --force --use-existing-database
    "$typo3cmsBinary" configuration:set SYS/trustedHostsPattern ".*"
else
    "$typo3Binary" setup --no-interaction --force --quiet
fi
_done

# Import DB fixtures
for file in "$fixturePath"/*.sql; do
    _progress "Importing DB fixture \"$(basename "$file")\""
    mysql $dbCredentials "$dbName" < "$file"
    _done
done
